package org.vineflower.ideanotnull;

import org.jetbrains.java.decompiler.api.plugin.PluginOptions;
import org.jetbrains.java.decompiler.main.extern.IFernflowerPreferences;

public interface IdeaNotNullOptions {
  @IFernflowerPreferences.Name("Resugar Intellij IDEA @NotNull")
  @IFernflowerPreferences.Description("Resugar Intellij IDEA's code generated by @NotNull annotations.")
  @IFernflowerPreferences.ShortName("inn")
  @IFernflowerPreferences.Type(IFernflowerPreferences.Type.BOOLEAN)
  String IDEA_NOT_NULL_ANNOTATION = "resugar-idea-notnull";

  static void addDefaults(PluginOptions.AddDefaults cons) {
    cons.addDefault(IDEA_NOT_NULL_ANNOTATION, "1");
  }
}
